# -*- coding: utf-8 -*-
# Auto-generated by EverGIS Python API Generator
"""
Spatial Processing Core API

Version: 1.5.1.0
"""

from __future__ import annotations

# Main components
from ._generated.client import APIClient as Client
from ._generated.async_client import AsyncAPIClient as AsyncClient
from . import schemas as schemas
from ._generated.exceptions import ApiClientError

# Package version
__version__ = "1.5.1.0"

# Exported symbols
__all__ = [
    "Client",
    "AsyncClient",
    "schemas",
    "ApiClientError",
    "__version__",
]

# Export schemas submodule as part of the public API