# -*- coding: utf-8 -*-
# Auto-generated by EverGIS Python API Generator
"""
Spatial Processing Gateway API

Version: 1.5.1.0
"""

from __future__ import annotations

# Main components
from .client import APIClient as Client
from .async_client import AsyncAPIClient as AsyncClient
from .schemas import *

# Package version
__version__ = "1.5.1.0"

# Exported symbols
__all__ = [
    "Client",
    "AsyncClient",
    "__version__",
]

# Export schemas
from . import schemas
__all__.extend(schemas.__all__)